# This workflow configures the user-statistician with the
# dark color theme, but otherwise uses all of
# the defaults. It is configured on a daily schedule at 3am.

name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/dark.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      with:
        colors: dark
        hide-keys: general
        animated-language-chart: true
        top-icon: none
        small-title: true
        custom-title: 'The best way to predict the future is to invent it.'
        language-animation-speed: 10
        commit-message: 'Automated change by https://github.com/cicirello/user-statistician'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
